version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: api-gateway
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - redis
      - postgres
      - mongo
    ports:
      - '3000:3000'

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: auth-service
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres
    ports:
      - '3001:3001'

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: user-service
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres
      - redis
    ports:
      - '3002:3002'

  product-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: product-service
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres
      - redis
    ports:
      - '3003:3003'

  order-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: order-service
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres
      - redis
    ports:
      - '3004:3004'

  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: notification-service
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - mongo
    ports:
      - '3005:3005'

volumes:
  postgres-data:
  mongo-data:
  redis-data:
  rabbitmq-data:
